version: '2'
services:
  redis:
    image: redis
    networks:
      - app
    restart: always
  ztf-web-viewer-app:
    build: .
    environment:
      - PRODUCTS_URL=http://ztf-web-viewer-proxy-dev
      - LC_API_URL=http://db.ztf.snad.space
      - TNS_API_URL=https://wis-tns.weizmann.ac.il
    env_file:
      - secret.env # TNS_API_KEY
    networks:
      - app
    env_file:
      - secret.env
    depends_on:
      - redis
    restart: always
  ztf-web-viewer-proxy-dev:
    build: proxy
    volumes:
      - proxy-cache:/cache
    networks:
      - app
      - proxy
    environment:
      VIRTUAL_HOST: ztf-dev.snad.space
#      HTTPS_METHOD: noredirect
      DYNDNS_HOST: ztf-dev.snad.space
      LETSENCRYPT_HOST: ztf-dev.snad.space
      LETSENCRYPT_EMAIL: ztf-dev@homb.it
    depends_on:
      - ztf-web-viewer-app
    restart: always

volumes:
  proxy-cache:

networks:
  app:
  proxy:
    external:
      name: proxy
